# Generated by Django 4.1.3 on 2022-12-16 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.FileField(upload_to='items_photos'),
        ),
    ]
