# Generated by Django 4.1.3 on 2022-12-17 18:52

import django.core.validators
from django.db import migrations, models
import project_1.core.my_validators


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0005_alter_item_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'ordering': ['pk']},
        ),
        migrations.AlterModelOptions(
            name='itemimage',
            options={'ordering': ['pk']},
        ),
        migrations.AddField(
            model_name='item',
            name='date_of_publication',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='item',
            name='image_main',
            field=models.ImageField(default='defaults/no-img.png', upload_to='items_photos_mains'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='location',
            field=models.CharField(blank=True, max_length=60, validators=[django.core.validators.MinLengthValidator(2), project_1.core.my_validators.validate_location]),
        ),
    ]
