# Generated by Django 4.1.3 on 2022-12-17 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_item_options_alter_itemimage_options_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='date_of_publication',
            new_name='date_added',
        ),
    ]
