# Generated by Django 4.1.3 on 2022-12-20 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_remove_item_condition_item_is_new_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('animals', 'Animals'), ('real_estate', 'Real Estate'), ('babies', 'Babies'), ('house_garden', 'House and garden'), ('vehicles', 'Vehicles'), ('electronics', 'Electronics'), ('appearance', 'Appearance'), ('others', 'Others')], max_length=12),
        ),
    ]
